sudo: false
language: python
python:
- '3.6'
addons:
  ssh_known_hosts: moon.scs.ryerson.ca
install:
- pip install -r requirements.txt
script:
- py.test --cov-report term --cov=echobot/
env:
- CODECOV_TOKEN=4e3629d9-80e8-4f6a-80fb-0a5a81731004
after_success:
- codecov
dd:
- openssl aes-256-cbc -K $encrypted_db49419baf50_key -iv $encrypted_db49419baf50_iv
  -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
    provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet
        ./a2_index
        tturin@moon.scs.ryerson.ca:/home/avm/courses/cps847/tturin
    on:
        branch: master
