sudo: false
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- py.test --cov-report term --cov=echobot/
env:
- CODECOV_TOKEN=4e3629d9-80e8-4f6a-80fb-0a5a81731004
after_success:
- codecov
dd:
- openssl aes-256-cbc -K $encrypted_db49419baf50_key -iv $encrypted_db49419baf50_iv
  -in deploy_rsa.enc -out deploy_rsa -d
