sudo: false
language: python
python:
- '3.6'
addons:
  ssh_known_hosts: moon.scs.ryerson.ca
install:
- pip install -r requirements.txt
script:
- py.test --cov-report term --cov=echobot/
env:
  matrix:
  - CODECOV_TOKEN=4e3629d9-80e8-4f6a-80fb-0a5a81731004
  global:
    secure: jYhG5Ow7oIcDxZZpsBodxI+KrMkhP+EoUw0DkHsxoDB+SDc0n42jBVnEIELIwjKgxPgPGZ5IWYIoSh4evW2+98UnkwqGE5+dC/pnH8zp7DjX9pSGXeSG3lk1FPylFHFTZ/yp+OhijWBRb+s7EZwR9un3J+2alSDvb1DGVa0SiCgyIDqs+tSrazPcn1AkCK0bOf3f9FBIx/5Cihkk0RxEuwwhiWTDU7PHVZtMTBdU+8geb66o2blg+rb658levWp0XqXAPibAUNXLX8Njn5/iOu74CTwh00P0sBd63l8R6M3Q5I44jv72FsNsHg0Dmw+QDHPt+e2ZP3m8jl9PkHC+mZ8M0BhMu3bYDT9/Zi5BJJsqiQ9p95WGNmT8mQANBcylu9u9n1JBhGkUuQGYRIS3TGDBCpdCK0D1dzchAVcimKRo+V3uXjWR+8zN8nXXUCiijO3iKzcq3IYms+ELEfTEn7LhdcZ2o9RTUvJ56lXhld1LWpPNUhbFtM+lnWmeOxCQ1vwq3tUItC76Cbeq1KI8qodSQ5+j8C9B18j84By3DhV/mHpb6G2lOUmIKH88XsCuvJlCpTIEeY1+ss37XNC1w7FCnjzc4Dcd6u6OxvIMvsPU7DLwFPenw+U5cFhRxT1jwIaoBNmmaqr6Hu8WhQWg3gOJAuqYA/FC4g9f4i6GHeg=
after_success:
- codecov
before_deploy:
- openssl aes-256-cbc -k "asdfasdf" -i new_deploy.enc -out /tmp/new_deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/new_deploy
- ssh-add /tmp/new_deploy
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet ./a2_index tturin@moon.scs.ryerson.ca:/home/avm/courses/cps847/tturin
  on:
    branch: master
